// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ModifierGroup struct {
	ID   uuid.UUID
	Name string
}

type ModifierOption struct {
	ID              uuid.UUID
	Name            string
	PriceAdjustment string
	ModifierGroupID uuid.UUID
}

type Order struct {
	ID        uuid.UUID
	CreatedAt time.Time
	Total     string
}

type OrderItem struct {
	ID              uuid.UUID
	OrderID         uuid.UUID
	ProductID       uuid.UUID
	Quantity        int32
	PriceAtPurchase string
}

type OrderItemsModifier struct {
	OrderItemID               uuid.UUID
	ModifierOptionID          uuid.UUID
	PriceAdjustmentAtPurchase string
}

type Product struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Count     sql.NullInt32
	Price     string
}

type ProductModifierGroup struct {
	ProductID       uuid.UUID
	ModifierGroupID uuid.UUID
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Name           string
	HashedPassword string
}
