// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: modifiers.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createModifierGroup = `-- name: CreateModifierGroup :one
INSERT INTO modifier_groups(id, name)
VALUES (
    $1,
    $2
)
RETURNING id, name
`

type CreateModifierGroupParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateModifierGroup(ctx context.Context, arg CreateModifierGroupParams) (ModifierGroup, error) {
	row := q.db.QueryRowContext(ctx, createModifierGroup, arg.ID, arg.Name)
	var i ModifierGroup
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createModifierOption = `-- name: CreateModifierOption :one
INSERT INTO modifier_options(id, name, price_adjustment, modifier_group_id)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, name, price_adjustment, modifier_group_id
`

type CreateModifierOptionParams struct {
	ID              uuid.UUID
	Name            string
	PriceAdjustment sql.NullString
	ModifierGroupID uuid.UUID
}

func (q *Queries) CreateModifierOption(ctx context.Context, arg CreateModifierOptionParams) (ModifierOption, error) {
	row := q.db.QueryRowContext(ctx, createModifierOption,
		arg.ID,
		arg.Name,
		arg.PriceAdjustment,
		arg.ModifierGroupID,
	)
	var i ModifierOption
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceAdjustment,
		&i.ModifierGroupID,
	)
	return i, err
}

const getAllModifierGroupsForProduct = `-- name: GetAllModifierGroupsForProduct :many
SELECT modifier_groups.id, modifier_groups.name FROM product_modifier_groups
INNER JOIN modifier_groups
    ON product_modifier_groups.modifier_group_id = modifier_groups.id
WHERE $1 = product_modifier_groups.product_id
`

func (q *Queries) GetAllModifierGroupsForProduct(ctx context.Context, productID uuid.UUID) ([]ModifierGroup, error) {
	rows, err := q.db.QueryContext(ctx, getAllModifierGroupsForProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModifierGroup
	for rows.Next() {
		var i ModifierGroup
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllOptionsForModifierGroup = `-- name: GetAllOptionsForModifierGroup :many
SELECT id, name, price_adjustment, modifier_group_id FROM modifier_options
WHERE $1 = modifier_group_id
`

func (q *Queries) GetAllOptionsForModifierGroup(ctx context.Context, modifierGroupID uuid.UUID) ([]ModifierOption, error) {
	rows, err := q.db.QueryContext(ctx, getAllOptionsForModifierGroup, modifierGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModifierOption
	for rows.Next() {
		var i ModifierOption
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceAdjustment,
			&i.ModifierGroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIdForGroup = `-- name: GetIdForGroup :one
SELECT id FROM modifier_groups
WHERE $1 = name
`

func (q *Queries) GetIdForGroup(ctx context.Context, name string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getIdForGroup, name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const linkModifierGroupToProduct = `-- name: LinkModifierGroupToProduct :exec
INSERT INTO product_modifier_groups(product_id, modifier_group_id)
VALUES (
    $1,
    $2
)
`

type LinkModifierGroupToProductParams struct {
	ProductID       uuid.UUID
	ModifierGroupID uuid.UUID
}

func (q *Queries) LinkModifierGroupToProduct(ctx context.Context, arg LinkModifierGroupToProductParams) error {
	_, err := q.db.ExecContext(ctx, linkModifierGroupToProduct, arg.ProductID, arg.ModifierGroupID)
	return err
}
