// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addItemToOrder = `-- name: AddItemToOrder :one
INSERT INTO order_items (id, order_id, product_id, quantity, price_at_purchase)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, order_id, product_id, quantity, price_at_purchase
`

type AddItemToOrderParams struct {
	ID              uuid.UUID
	OrderID         uuid.UUID
	ProductID       uuid.UUID
	Quantity        int32
	PriceAtPurchase string
}

func (q *Queries) AddItemToOrder(ctx context.Context, arg AddItemToOrderParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, addItemToOrder,
		arg.ID,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.PriceAtPurchase,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.PriceAtPurchase,
	)
	return i, err
}

const addModifierToOrderItem = `-- name: AddModifierToOrderItem :exec
INSERT INTO order_items_modifiers (order_item_id, modifier_option_id, price_adjustment_at_purchase)
VALUES (
    $1,
    $2,
    $3
)
RETURNING order_item_id, modifier_option_id, price_adjustment_at_purchase
`

type AddModifierToOrderItemParams struct {
	OrderItemID               uuid.UUID
	ModifierOptionID          uuid.UUID
	PriceAdjustmentAtPurchase string
}

func (q *Queries) AddModifierToOrderItem(ctx context.Context, arg AddModifierToOrderItemParams) error {
	_, err := q.db.ExecContext(ctx, addModifierToOrderItem, arg.OrderItemID, arg.ModifierOptionID, arg.PriceAdjustmentAtPurchase)
	return err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders(id, created_at, total)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, created_at, total
`

type CreateOrderParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	Total     string
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder, arg.ID, arg.CreatedAt, arg.Total)
	var i Order
	err := row.Scan(&i.ID, &i.CreatedAt, &i.Total)
	return i, err
}

const getAllItemsInOrder = `-- name: GetAllItemsInOrder :many
SELECT order_items.quantity, order_items.price_at_purchase, products.name
FROM order_items
INNER JOIN products
    ON order_items.product_id = products.id
WHERE order_items.order_id = $1
`

type GetAllItemsInOrderRow struct {
	Quantity        int32
	PriceAtPurchase string
	Name            string
}

func (q *Queries) GetAllItemsInOrder(ctx context.Context, orderID uuid.UUID) ([]GetAllItemsInOrderRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllItemsInOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllItemsInOrderRow
	for rows.Next() {
		var i GetAllItemsInOrderRow
		if err := rows.Scan(&i.Quantity, &i.PriceAtPurchase, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
