// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (id, created_at, updated_at, name, count, price)
VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6
)
RETURNING id, created_at, updated_at, name, count, price
`

type CreateProductParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Count     sql.NullInt32
	Price     sql.NullString
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Count,
		arg.Price,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Count,
		&i.Price,
	)
	return i, err
}

const deleteAllProducts = `-- name: DeleteAllProducts :exec
DELETE FROM products
`

func (q *Queries) DeleteAllProducts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllProducts)
	return err
}
